name: Java CI

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      
      - name: 'Products'
        run:
          cd ./3.1;
          mvn -B clean compile test install;
          cd ../
      
      - name: 'Filters'
        run:
          cd ./3.2;
          mvn -B clean compile test install;
          cd ../
    
      - name: 'ProductsService'
        run: 
          cd ./3.3;
          mvn -B clean compile test;
          cd ../
